<?php
    $request = Zend_Controller_Front::getInstance()->getRequest();
?><!doctype html>
<html lang="en" class="no-js"><head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
	<title>Zend Starter Application</title>
	<meta name="description" content="">
	<meta name="author" content="">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link rel="shortcut icon" href="/favicon.ico">
	<link rel="stylesheet" href="css/style.css?v=2">

</head>
<body>
	<div id="container">
		<header>

		</header>

		<div id="main" role="main">

            <?php echo $this->layout()->content; ?>

		</div>

		<footer>

		</footer>
	</div>
</body>
</html>
